# We can install specify version golang in task, like this:
#- roles:
#  - role: install-golang
#      go_version: '1.10.1'
---
- name: Download the Go version {{ go_version }} tarball
  get_url:
    url: '{{ go_download_location }}'
    dest: '/usr/local/src/{{ go_tarball }}'

- name: Remove old installation of Go
  file:
    path: /usr/local/go
    state: absent

- name: Extract the Go tarball to place
  unarchive:
    src: '/usr/local/src/{{ go_tarball }}'
    dest: /usr/local
    remote_src: yes
